-- Copyright (c) 2026 LLVM-MOS Project
--
-- Licensed under the Apache License, Version 2.0 with LLVM Exceptions.
-- See https://github.com/llvm-mos/llvm-mos-sdk/blob/main/LICENSE for license
-- information.
--
-- Generates _ram-banked.ld for the mega65-banked platform.
-- Usage: lua generate-banked-sections.lua > ../_ram-banked.ld
--        lua generate-banked-sections.lua output  (prints OUTPUT_FORMAT lines)
--
-- SYNC: see _ram-banked.ld header for the full list of files encoding bank layout.

local BANK_MAX = 15
local BANK_SIZE = 0x6000   -- 24KB per bank
local BANK_WINDOW = 0x2000 -- VMA of the banked window

local function printf(...)
  print(string.format(table.unpack({...})))
end

local args = {...}
if args[1] == "output" then
  -- Print OUTPUT_FORMAT FULL() lines for each bank region
  for i = 1, BANK_MAX do
    printf("  FULL(bank_%d)", i)
  end
  return
end

print("/* Automatically generated by generate-banked-sections.lua.")
print(" *")
print(" * LMAs use lower-16 = $2000 so symbols resolve to the banked window.")
print(" * Upper bits are sequential and only affect PRG file layout.")
print(" *")
print(" * SYNC: see _ram-banked.ld header for the full list of files encoding bank layout.")
print(" */\n")

-- LMA declarations: sequential $0N2000 values (upper bits just need to be unique)
for i = 1, BANK_MAX do
  printf("__bank_%d_lma = 0x%06x;", i, i * 0x010000 + BANK_WINDOW)
end
print()

-- MEMORY regions for banks 1-N.
printf("MEMORY {")
for i = 1, BANK_MAX do
  printf("  bank_%d : ORIGIN = __bank_%d_lma, LENGTH = 0x%04x", i, i, BANK_SIZE)
end
printf("}\n")

-- SECTIONS: each bank gets its own section placed in its memory region.
printf("SECTIONS {")
for i = 1, BANK_MAX do
  printf("  .bank_%d : { *(.bank_%d .bank_%d.*) } >bank_%d", i, i, i, i)
end
printf("}\n")

-- SIZEOF symbols for CRT bank loader (skip empty banks).
for i = 1, BANK_MAX do
  printf("__bank_%d_size = SIZEOF(.bank_%d);", i, i)
end
